<a href="https://colab.research.google.com/github/yyj0128/MachineLearning/blob/main/chapter6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **ch6. 머신러닝 데이터 살펴보기**



## 6.1 머신러닝에 사용할 데이터 소개


In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import datasets

In [ ]:
raw_boston=datasets.load_boston()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [ ]:
X_boston = pd.DataFrame(raw_boston.data)
y_boston = pd.DataFrame(raw_boston.target)
df_boston = pd.concat([X_boston, y_boston], axis=1)

In [ ]:
len(df_boston)

506

In [ ]:
df_boston.head()

0     1     2    3      4      5   ...   8      9     10      11    12    0 
0  0.00632  18.0  2.31  0.0  0.538  6.575  ...  1.0  296.0  15.3  396.90  4.98  24.0
1  0.02731   0.0  7.07  0.0  0.469  6.421  ...  2.0  242.0  17.8  396.90  9.14  21.6
2  0.02729   0.0  7.07  0.0  0.469  7.185  ...  2.0  242.0  17.8  392.83  4.03  34.7
3  0.03237   0.0  2.18  0.0  0.458  6.998  ...  3.0  222.0  18.7  394.63  2.94  33.4
4  0.06905   0.0  2.18  0.0  0.458  7.147  ...  3.0  222.0  18.7  396.90  5.33  36.2

[5 rows x 14 columns]

In [ ]:
feature_boston = raw_boston.feature_names
print(feature_boston)

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [ ]:
col_boston = np.append(feature_boston, ['target'])
df_boston.columns = col_boston
df_boston.head()

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  target
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98    24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14    21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03    34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94    33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33    36.2

[5 rows x 14 columns]

## 6.2 데이터 전처리

### 6.2.1 결측치 처리

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
## 데이터 생성
df = pd.DataFrame([
    [42, 'male', 12, 'reading', 'class2'],
    [35, 'unknown', 3, 'cooking', 'class1'],
    [1000, 'female', 7, 'cycling', 'class3'],
    [1000, 'unknown', 21, 'unknown', 'unknown']
])
df.columns = ['age', 'gender', 'month_birth', 'hobby', 'target']

In [ ]:
df['age'].unique()

array([  42,   35, 1000])

In [ ]:
df['gender'].unique()

array(['male', 'unknown', 'female'], dtype=object)

In [ ]:
df['month_birth'].unique()

array([12,  3,  7, 21])

In [ ]:
df['hobby'].unique()

array(['reading', 'cooking', 'cycling', 'unknown'], dtype=object)

In [ ]:
df['target'].unique()

array(['class2', 'class1', 'class3', 'unknown'], dtype=object)

In [ ]:
# age가 150보다 큰것 결측치로 만들기

df.loc[df['age']>150, ['age']] = np.nan

In [ ]:
df.loc[df['gender']=='unknown', ['gender']] = np.nan

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
df.loc[df['month_birth'] > 12, ['month_birth']] = np.nan

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
df.loc[df['hobby']=='unknown', ['hobby']] = np.nan

In [ ]:
df.loc[df['target']=='unknown'] = np.nan

In [ ]:
df.isnull().sum()

age            2
gender         2
month_birth    1
hobby          1
target         1
dtype: int64

In [ ]:
df2 = df.dropna(axis=0)  # 결측치를 포함한 행 삭제
df2

age gender  month_birth    hobby  target
0  42.0   male         12.0  reading  class2

In [ ]:
df3 = df.dropna(axis=1)  # 결측치를 포함한 열 삭제
df3

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [ ]:
df4 = df.dropna(how='all')  # 모든 값이 결측치인 행 삭제
df4

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading  class2
1  35.0     NaN          3.0  cooking  class1
2   NaN  female          7.0  cycling  class3

In [ ]:
df5 = df.dropna(thresh=2)  # 값이 2개 미만인 행 삭제
df5

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading  class2
1  35.0     NaN          3.0  cooking  class1
2   NaN  female          7.0  cycling  class3

In [ ]:
df6 = df.dropna(subset=['gender'])   # gender컬럼에 결측치가 있는 행 삭제
df6

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading  class2
2   NaN  female          7.0  cycling  class3

In [ ]:
alter_values = {'age':0,
                'gender': 'U',
                'month_birth':0,
                'hobby': 'U',
                'target': 'class4'}
df7 = df.fillna(alter_values)   # alter_values의 값으로 결측치 대체
df7

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading  class2
1  35.0       U          3.0  cooking  class1
2   0.0  female          7.0  cycling  class3
3   0.0       U          0.0        U  class4

### 6.2.2 클래스 라벨 설정


In [ ]:
# 사이킷런 사용한 라벨링

from sklearn.preprocessing import LabelEncoder
df8 = df7
class_label = LabelEncoder()  # 라벨링 모형 생성
data_value = df8['target'].values    # 타깃변수 추출
y_new = class_label.fit_transform(data_value)   # 타깃변수(target)를 라벨링 모형에 넣고 변환 (클래스 라벨링)
y_new

array([1, 0, 2, 3])

In [ ]:
# 라벨링한 데이터 원상복구
y_ori = class_label.inverse_transform(y_new)  
y_ori
df8['target'] = y_ori
df8

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading  class2
1  35.0       U          3.0  cooking  class1
2   0.0  female          7.0  cycling  class3
3   0.0       U          0.0        U  class4

In [ ]:
# 사이킷런을 사용하지 않고 라벨링
y_arr = df8['target'].values
new_y_arr = sorted(y_arr)

num_y = 0
dic_y ={}
for ith_y in new_y_arr:
  dic_y[ith_y] = num_y
  num_y +=1

dic_y

{'class1': 0, 'class2': 1, 'class3': 2, 'class4': 3}

In [ ]:
df8['target'] = df8['target'].replace(dic_y)
df8

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading       1
1  35.0       U          3.0  cooking       0
2   0.0  female          7.0  cycling       2
3   0.0       U          0.0        U       3

### 6.2.3 원-핫 인코딩

In [ ]:
df9 = df8.copy()

In [ ]:
# 타깃변수만 원핫인코딩
df9['target'] = df9['target'].astype(str)

df10 = pd.get_dummies(df9['target'])  
print(df10)

   0  1  2  3
0  0  1  0  0
1  1  0  0  0
2  0  0  1  0
3  0  0  0  1


In [ ]:
# 모든컬럼 원핫인코딩
df11 = df8
df12 = pd.get_dummies(df11)
df12

age  month_birth  target  ...  hobby_cooking  hobby_cycling  hobby_reading
0  42.0         12.0       1  ...              0              0              1
1  35.0          3.0       0  ...              1              0              0
2   0.0          7.0       2  ...              0              1              0
3   0.0          0.0       3  ...              0              0              0

[4 rows x 10 columns]

In [ ]:
# 사이킷런을 이용한 원-핫 인코딩

from sklearn.preprocessing import OneHotEncoder
hot_encoder = OneHotEncoder()

y = df7[['target']]
y_hot = hot_encoder.fit_transform(y)
print(y_hot.toarray())

[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# 텐서플로우를 이룡한 원-핫 인코딩

from tensorflow.keras.utils import to_categorical

y_hotec = to_categorical(y)
print(y_hotec)

[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 6.2.4 데이터 스케일링



#### # 데이터 스케일링 : 데이터 값이 단위에 영향을 받지 않도록 변형하는 것 


1) 표준화 스케일링 : 

평균이 0, 표준편차가 1이 되도록 변경하는 방법

In [ ]:
# 표준화 스케일링

from sklearn.preprocessing import StandardScaler

std = StandardScaler()
std.fit(df8[['month_birth']])
x_std = std.transform(df8[['month_birth']])

print(x_std)
print(np.mean(x_std))
print(np.std(x_std))

[[ 1.44444444]
 [-0.55555556]
 [ 0.33333333]
 [-1.22222222]]
-5.551115123125783e-17
1.0




2) 로버스트 스케일링 : 

표준화 스케일을 변형한 방법. 중앙값과 사분위수를 사용하며, 극단값의 영향을 거의 받지 않는다는 장점이 있음

In [ ]:
# 로버스트 스케일링
from sklearn.preprocessing import RobustScaler

robust = RobustScaler()
robust.fit(df8[['month_birth']])

x_robust = robust.transform(df8[['month_birth']])

print(x_robust)


[[ 1.16666667]
 [-0.33333333]
 [ 0.33333333]
 [-0.83333333]]


3) 최소-최대 스케일링 : 

데이터의 최댓값이 1, 최속값이 0으로 데이터가 가질 수 있는 범위를 제한하는 방법

In [ ]:
# 최소-최대 스케일링

from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()
minmax.fit(df8[['month_birth']])
x_minmax = minmax.transform(df8[['month_birth']])

print(x_minmax)

[[1.        ]
 [0.25      ]
 [0.58333333]
 [0.        ]]



4) 노멀 스케일링 : 

벡터의 유클리디안 길이가 1이 되도록 데이터값 변경 (주로 벡터의 길이는 상관 없고, 방향(각도)만 고려할 때 사용)





In [ ]:
# 노멀 스케일링

from sklearn.preprocessing import Normalizer

normal = Normalizer()
normal.fit(df8[['age', 'month_birth']])
x_normal = normal.transform(df8[['age', 'month_birth']])

print(x_normal)

[[0.96152395 0.27472113]
 [0.99634665 0.08540114]
 [0.         1.        ]
 [0.         0.        ]]



*  표준화, 로버스트, 최소-최대 스케일링 : 열 기준 </br>

*  노멀 스케일링 : 행 기준